import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
realtek/8711b/cmsis/device/system_8195a.c
realtek/8711b/fwlib/ram_lib/rtl8710b_pinmapcfg.c
realtek/8711b/fwlib/ram_lib/rtl8710b_intfcfg.c
realtek/8711b/app/monitor/ram/rtl_consol.c
realtek/8711b/app/monitor/ram/monitor.c
""")

path = [cwd,
    cwd + '/realtek/8711b/cmsis',
    cwd + '/realtek/8711b/misc',
    cwd + '/realtek/8711b/fwlib/include', 
    cwd + '/realtek/8711b/cmsis/device',
    cwd + '/realtek/8711b/swlib/rtl_lib',
    cwd + '/realtek/8711b/app/monitor/include',
    cwd + '/realtek/8711b/swlib/std_lib/include',
    cwd + '/realtek/8711b/swlib/std_lib/libc/rom/string']

CPPDEFINES = ['CONFIG_PLATFORM_8711B']

LIB = ['lib_platform', 'lib_rtlstd', 'lib_wlan', 'lib_wps']
if rtconfig.CROSS_TOOL == 'gcc':
	LIB_PATH = [cwd + '/realtek/8711b/misc/bsp/lib/common/GCC']
	LIB += ['lib_dct', '-lnosys']
elif rtconfig.CROSS_TOOL == 'iar':
	LIB_PATH = [cwd + '/realtek/8711b/misc/bsp/lib/common/IAR']
	CPPDEFINES += ['__IEEE_LITTLE_ENDIAN']

group = DefineGroup('soc_8711b', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES, LIBS = LIB, LIBPATH = LIB_PATH)

Return('group')
