import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
path =[cwd + '/platform',
	cwd + '/']

src = []
if GetDepend(['RT_USING_LWIP']):
	src += Split('''
		wifi/wifi_ind.c
		wifi/wifi_util.c
		wifi/wifi_promisc.c
		wifi/rtw_wpa_supplicant/wpa_supplicant/wifi_eap_config.c
	''')

	path += [cwd + '/wifi',
		cwd + '/wifi/rtw_wpa_supplicant/src',
		cwd + '/../drivers/wlan/realtek/include',
		cwd + '/../drivers/wlan/realtek/src/osdep',
		cwd + '/../drivers/wlan/realtek/wlan_ram_map/rom',
		cwd + '/../network/ssl/polarssl-1.3.8/include',
		cwd + '/../network/ssl/ssl_ram_map/rom']

group = DefineGroup('ameba_wifi', src, depend = [], CPPPATH = path)

Return('group')
