import rtconfig
from building import *

cwd = GetCurrentDir()

src = Split('''
	os/rtthread_service.c
	realtek/8711b/rtl8710b_startup.c
	realtek/8711b/app_start.c
	realtek/common/wifi/wifi_conf.c
	''')

path = [cwd, 
	cwd + '/os',
	cwd + '/realtek/8711b/include']

group = DefineGroup('rtt_patch', src, depend = [''], CPPPATH = path)

Return('group')
