import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split('''
	os_dep/osdep_service.c
''')

path = [cwd + '/os_dep/include',
	cwd + '/freertos',
	cwd + '/freertos/freertos_v8.1.2/Source/include']

if rtconfig.CROSS_TOOL == 'gcc':
	path += [cwd + '/freertos/freertos_v8.1.2/Source/portable/GCC/ARM_CM4F']
elif rtconfig.CROSS_TOOL == 'iar':
	path += [cwd + '/freertos/freertos_v8.1.2/Source/portable/IAR/ARM_CM4F']

group = DefineGroup('os_dep', src, depend = [''], CPPPATH = path)

Return('group')
